=== irmtim/TypiconOnline.Documentation/XML/Examples/RulesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by imtim (imtim company) -->
<!--W3C Schema generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rule" type="executableType"/>
	<xs:complexType name="switchType">
		<xs:sequence>
			<xs:element name="condition" type="valueType"/>
			<xs:element name="case" type="caseType" maxOccurs="unbounded"/>
			<xs:element name="default" type="executableType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="daysfromeasterType">
		<xs:choice>
			<xs:element ref="date" minOccurs="0"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="datebydaysfromeaster" type="intOutputType"/>
	<xs:element name="getclosestday" type="getClosestDayType"/>
	<xs:complexType name="modifydayType">
		<xs:sequence>
			<xs:element ref="getclosestday" minOccurs="0"/>
			<xs:element ref="date" minOccurs="0"/>
			<xs:element ref="datebydaysfromeaster" minOccurs="0"/>
			<xs:element name="modifyreplacedday" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="modifydayType">
							<xs:attribute name="kind" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="menology"/>
										<xs:enumeration value="triodion"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="asaddition" type="xs:boolean" use="optional"/>
		<xs:attribute name="daymove" type="xs:byte" use="optional"/>
		<xs:attribute name="shortname" type="xs:string" use="optional"/>
		<xs:attribute name="priority" type="xs:int" use="optional"/>
		<xs:attribute name="islastname" type="xs:boolean"/>
		<xs:attribute name="usefullname" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="valueType">
		<xs:choice>
			<xs:element name="daysfromeaster" type="daysfromeasterType" minOccurs="0"/>
			<xs:element ref="date" minOccurs="0"/>
			<xs:element name="int" type="xs:int" minOccurs="0"/>
			<xs:element name="getclosestday" type="getClosestDayType" minOccurs="0"/>
			<xs:element name="getdayofweek" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="getdayofweekType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="getdayofweekType">
		<xs:sequence>
			<xs:element ref="date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="getclosestday" type="getClosestDayType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="valuesType">
		<xs:sequence>
			<xs:element name="daysfromeaster" type="daysfromeasterType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="int" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="getclosestday" type="getClosestDayType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="getdayofweek" type="getdayofweekType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="caseType">
		<xs:sequence>
			<xs:element name="values" type="valuesType"/>
			<xs:element name="action" type="executableType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="executableType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="modifyday" type="modifydayType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="switch" type="switchType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="if" type="ifType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="service" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="executableType">
							<xs:attribute name="time" type="xs:string" use="optional"/>
							<xs:attribute name="timestyle" type="xs:string" use="optional"/>
							<xs:attribute name="name" type="xs:string" use="required"/>
							<xs:attribute name="namestyle" type="xs:string" use="optional"/>
							<xs:attribute name="isdaybefore" type="xs:boolean" use="optional" default="false"/>
							<xs:attribute name="additionalname" type="xs:string" use="optional"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="notice" type="noticeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="text" type="textType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="getClosestDayType">
		<xs:choice>
			<xs:element ref="date" minOccurs="0"/>
		</xs:choice>
		<xs:attribute name="dayofweek" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="понедельник"/>
					<xs:enumeration value="вторник"/>
					<xs:enumeration value="среда"/>
					<xs:enumeration value="четверг"/>
					<xs:enumeration value="пятница"/>
					<xs:enumeration value="суббота"/>
					<xs:enumeration value="воскресенье"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="weekcount" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:element name="date" type="xs:gMonthDay"/>
	<xs:element name="daysfromeaster" type="daysfromeasterType"/>
	<xs:element name="int" type="xs:int"/>
	<xs:complexType name="noticeType">
		<xs:attribute name="time" type="xs:string" use="optional"/>
		<xs:attribute name="timestyle" type="xs:string" use="optional"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="namestyle" type="xs:string" use="optional"/>
		<xs:attribute name="isdaybefore" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="additionalname" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="intOutputType">
		<xs:choice>
			<xs:element ref="daysfromeaster" minOccurs="0"/>
			<xs:element ref="int" minOccurs="0"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="textType">
		<xs:sequence>
			<xs:element name="style" type="styleType"/>
			<xs:element name="text"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="styleType">
		<xs:sequence>
			<xs:element name="red" minOccurs="0" maxOccurs="1"/>
			<xs:element name="bold" minOccurs="0" maxOccurs="1"/>
			<xs:choice minOccurs="0" maxOccurs="1">
				<xs:element name="h1"/>
				<xs:element name="h2"/>
				<xs:element name="h3"/>
				<xs:element name="h4"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ifType">
		<xs:sequence>
			<xs:element name="condition" type="boolValueType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="then" type="executableType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="else" type="executableType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="boolValueType">
		<xs:sequence>
			<xs:element name="equals" type="comparisonType" minOccurs="0"/>
			<xs:element name="more" type="comparisonType" minOccurs="0"/>
			<xs:element name="moreequals" type="comparisonType" minOccurs="0"/>
			<xs:element name="less" type="comparisonType" minOccurs="0"/>
			<xs:element name="lessequals" type="comparisonType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="comparisonType">
		<xs:sequence>
			<xs:element name="op1" type="valueType"/>
			<xs:element name="op2" type="valueType"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Menology/--02-15.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Rules/RulesSchema.xsd">
	<if>
		<expression>
			<less>
				<daysfromeaster>
					<date>--02-15</date>
				</daysfromeaster>
				<int>-70</int>
			</less>
		</expression>
		<then>
			<!-- Обычное бдение с литией-->
			<service time="16.00" name="Всенощное бдение." isdaybefore="true"/>
			<service time="08.40" name="Часы 3-й и 6-й."/>
			<service time="09.00" name="Божественная литургия."/>
		</then>
		<else>
			<switch>
				<expression>
					<daysfromeaster>
						<date>--02-15</date>
					</daysfromeaster>
				</expression>
				<!-- Соединение с воскресной службой -->
				<case>
					<values>
						<int>-70</int>
						<int>-63</int>
						<int>-56</int>
						<int>-49</int>
					</values>
					<action>
						<service time="16.00" name="Всенощное бдение." isdaybefore="true"/>
						<service time="08.40" name="Часы 3-й и 6-й."/>
						<service time="09.00" name="Божественная литургия."/>
					</action>
				</case>
				<!-- Служба праздника совершается в этот день.
					  Перенос заупокойной службы на субботу предыдущую -->
				<case>
					<values>
						<int>-57</int>
					</values>
					<action>
						<modifyday daymove="0">
							<modifyreplacedday kind="triodion" daymove="-7"/>
						</modifyday>
						<service time="16.00" name="Всенощное бдение." isdaybefore="true"/>
						<service time="08.40" name="Часы 3-й и 6-й."/>
						<service time="09.00" name="Божественная литургия."/>
					</action>
				</case>
				<!-- Служба праздника совершается в этот день.
						Триодь опускается.-->
				<case>
					<values>
						<int>-55</int>
						<int>-54</int>
						<int>-52</int>
					</values>
					<action>
						<service time="16.00" name="Всенощное бдение." isdaybefore="true"/>
						<service time="08.40" name="Часы 3-й и 6-й."/>
						<service time="09.00" name="Божественная литургия."/>
					</action>
				</case>
				<case>
					<values>
						<int>-53</int>
						<int>-51</int>
					</values>
					<action>
						<service time="16.00" name="Всенощное бдение." isdaybefore="true"/>
						<service time="08.40" name="Часы 3-й и 6-й."/>
						<service time="09.00" name="Божественная литургия."/>
					</action>
				</case>
				<!-- Служба праздника совершается в этот день в соединении со службой Триоди.-->
				<case>
					<values>
						<int>-50</int>
					</values>
					<action>
						<modifyday daymove="0" priority="4"/>
						<service time="16.00" name="Всенощное бдение." isdaybefore="true"/>
						<service time="08.40" name="Часы 3-й и 6-й."/>
						<service time="09.00" name="Божественная литургия."/>
					</action>
				</case>
				<!-- Служба праздника совершается в этот день в соединении со службой Триоди.-->
				<case>
					<values>
						<int>-48</int>
					</values>
					<action>
						<modifyday daymove="0" priority="3"/>
						<service time="16.00" name="Всенощное бдение." isdaybefore="true"/>
						<service time="08.40" name="Часы 3-й и 6-й."/>
						<service time="09.00" name="Божественная литургия."/>
					</action>
				</case>
				<case>
					<values>
						<int>-17</int>
					</values>
					<action>
						<modifyday daymove="-2" priority="3"/>
						<service time="17.30" name="9-й час.  Вечерня. Малое повечерие." isdaybefore="true"/>
						<service time="06.00" name="Полунощница. Утреня. Часы."/>
						<service time="09.00" name="Литургия Преждеосвященных Даров."/>
					</action>
				</case>
				<default>
					<modifyday priority="3"/>
					<service time="17.30" name="Великое повечерие." isdaybefore="true"/>
					<service time="06.00" name="Полунощница. Утреня. Часы."/>
					<service time="09.00" name="Литургия Преждеосвященных Даров."/>
				</default>
			</switch>
		</else>
	</if>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Menology/Суббота пред Богоявлением.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Programming/Documentation/TypiconOnline.Documentation/XML/Rules/RulesSchema.xsd">
	<switch>
		<expression>
			<getdayofweek><date>--01-07</date></getdayofweek>
		</expression>
		<case>
			<values>
					<getdayofweek name="понедельник"></getdayofweek>
					<getdayofweek name="воскресенье"></getdayofweek>
					<getdayofweek name="суббота"></getdayofweek>
			</values>
			<action>
				
				
			</action>
		</case>
		<default>
			<modifyday priority="6" asaddition="true">
				<getclosestday dayofweek="суббота" weekcount="-1"><date>--01-19</date></getclosestday>
			</modifyday>
		</default>
	</switch>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Menology/--02-14.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Rules/RulesSchema.xsd">
	<switch>
		<expression>
			<daysfromeaster>
				<date>--02-14</date>
			</daysfromeaster>
		</expression>
		<!-- В Субботу мясопустную -->
		<case>
			<values>
				<int>-57</int>
			</values>
			<action>
				<modifyday daymove="-1" asaddition="true"/>
			</action>
		</case>
		<!-- Соединение с триодью. Фильтр: оставляем только прездпразднество -->
		<case>
			<values>
				<int>-50</int>
			</values>
			<action>
				<modifyday iscelebrating="true" daymove="0"/>
			</action>
		</case>
	</switch>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Examples/Молебен.1 вскр июня.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Programming/Documentation/TypiconOnline.Documentation/XML/Rules/RulesSchema.xsd">
	<if>
		<expression>
			<equals>
				<getclosestday dayofweek="воскресенье" weekcount="1">
					<date>--05-31</date>
				</getclosestday>
				<date/>
			</equals>
		</expression>
		<then>
			<worship id="moleben">
				<name>Молебен на день деревни.</name>
			</worship>
		</then>
	</if>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Sign/Бдение.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Programming/Documentation/TypiconOnline.Documentation/XML/Rules/RulesSchema.xsd">
	<worship time="16.00" mode="daybefore">
		<name>
			<item language="cs-ru">Всенощное бдение.</item>
		</name>
	</worship>
	<worship time="08.40">
		<name>
			<item language="cs-ru">Часы 3-й и 6-й.</item>
		</name>
	</worship>
	<worship time="09.00">
		<name>
			<item language="cs-ru">Божественная литургия.</item>
		</name>
	</worship>
	<!-- Если не в период Великого или Успенского постов -->
	<if>
		<expression>
			<or>
				<!-- между Великим и Успенским-->
				<and>
					<more>
						<date/>
						<datebydaysfromeaster>
							<int>7</int>
						</datebydaysfromeaster>
					</more>
					<less>
						<date/>
						<date>--08-14</date>
					</less>
				</and>
				<!-- между Новым годом и Великим постом-->
				<lessequals>
					<date/>
					<datebydaysfromeaster>
						<int>-49</int>
					</datebydaysfromeaster>
				</lessequals>
				<!-- между Успенским постом и Новым годом-->
				<more>
					<date/>
					<date>--08-28</date>
				</more>
			</or>
		</expression>
		<then>
			<!-- Если это воскресенье-->
			<if>
				<expression>
					<equals>
						<getdayofweek><date/></getdayofweek>
						<getdayofweek name="воскресенье"/>
					</equals>
				</expression>
				<then>
					<!-- Если это первое воскресенье месяца-->
					<if>
						<expression>
							<or>
								<equals>
									<getclosestday dayofweek="воскресенье" weekcount="1">
										<date>--12-31</date>
									</getclosestday>
									<date/>
								</equals>
								<equals>
									<getclosestday dayofweek="воскресенье" weekcount="1">
										<date>--01-31</date>
									</getclosestday>
									<date/>
								</equals>
								<equals>
									<getclosestday dayofweek="воскресенье" weekcount="1">
										<date>--02-28</date>
									</getclosestday>
									<date/>
								</equals>
								<equals>
									<getclosestday dayofweek="воскресенье" weekcount="1">
										<date>--03-31</date>
									</getclosestday>
									<date/>
								</equals>
								<equals>
									<getclosestday dayofweek="воскресенье" weekcount="1">
										<date>--04-30</date>
									</getclosestday>
									<date/>
								</equals>
								<equals>
									<getclosestday dayofweek="воскресенье" weekcount="1">
										<date>--05-31</date>
									</getclosestday>
									<date/>
								</equals>
								<equals>
									<getclosestday dayofweek="воскресенье" weekcount="1">
										<date>--06-30</date>
									</getclosestday>
									<date/>
								</equals>
								<equals>
									<getclosestday dayofweek="воскресенье" weekcount="1">
										<date>--07-31</date>
									</getclosestday>
									<date/>
								</equals>
								<equals>
									<getclosestday dayofweek="воскресенье" weekcount="1">
										<date>--08-31</date>
									</getclosestday>
									<date/>
								</equals>
								<equals>
									<getclosestday dayofweek="воскресенье" weekcount="1">
										<date>--09-30</date>
									</getclosestday>
									<date/>
								</equals>
								<equals>
									<getclosestday dayofweek="воскресенье" weekcount="1">
										<date>--10-31</date>
									</getclosestday>
									<date/>
								</equals>
								<equals>
									<getclosestday dayofweek="воскресенье" weekcount="1">
										<date>--11-30</date>
									</getclosestday>
									<date/>
								</equals>
							</or>
						</expression>
						<then>
							<worship id="moleben">
								<name>
									<item language="cs-ru">Молебен перед иконой Божией Матери "Всецарица".</item>
								</name>
							</worship>
						</then>
						<else>
							<worship id="moleben">
								<name>
									<item language="cs-ru">Общий молебен.</item>
								</name>
							</worship>
						</else>
					</if>
				</then>
			</if>
		</then>
	</if>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Examples/logical.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/%d0%9c%d0%be%d0%bd%d0%b0%d1%81%d1%82%d1%8b%d1%80%d1%8c/Documents/programming/XML/Rules/RulesSchema.xsd">
	<if>
		<expression>
			<equals>
				<int>1</int>
				<daysfromeaster>
					<date>--04-04</date>
				</daysfromeaster>
			</equals>
		</expression>
		<then/>
	</if>
</rule>
