=== irmtim/TypiconOnline.Documentation/XML/Examples/RulesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by imtim (imtim company) -->
<!--W3C Schema generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rule" type="executableType"/>
	<xs:complexType name="switchType">
		<xs:sequence>
			<xs:element name="condition" type="valueType"/>
			<xs:element name="case" type="caseType" maxOccurs="unbounded"/>
			<xs:element name="default" type="executableType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="daysfromeasterType">
		<xs:choice>
			<xs:element ref="date" minOccurs="0"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="datebydaysfromeaster" type="intOutputType"/>
	<xs:element name="getclosestday" type="getClosestDayType"/>
	<xs:complexType name="modifydayType">
		<xs:sequence>
			<xs:element ref="getclosestday" minOccurs="0"/>
			<xs:element ref="date" minOccurs="0"/>
			<xs:element ref="datebydaysfromeaster" minOccurs="0"/>
			<xs:element name="modifyreplacedday" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="modifydayType">
							<xs:attribute name="kind" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="menology"/>
										<xs:enumeration value="triodion"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="asaddition" type="xs:boolean" use="optional"/>
		<xs:attribute name="daymove" type="xs:byte" use="optional"/>
		<xs:attribute name="shortname" type="xs:string" use="optional"/>
		<xs:attribute name="priority" type="xs:int" use="optional"/>
		<xs:attribute name="islastname" type="xs:boolean"/>
		<xs:attribute name="usefullname" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="valueType">
		<xs:choice>
			<xs:element name="daysfromeaster" type="daysfromeasterType" minOccurs="0"/>
			<xs:element ref="date" minOccurs="0"/>
			<xs:element name="int" type="xs:int" minOccurs="0"/>
			<xs:element name="getclosestday" type="getClosestDayType" minOccurs="0"/>
			<xs:element name="getdayofweek" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="getdayofweekType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="getdayofweekType">
		<xs:sequence>
			<xs:element ref="date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="getclosestday" type="getClosestDayType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="valuesType">
		<xs:sequence>
			<xs:element name="daysfromeaster" type="daysfromeasterType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="int" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="getclosestday" type="getClosestDayType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="getdayofweek" type="getdayofweekType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="caseType">
		<xs:sequence>
			<xs:element name="values" type="valuesType"/>
			<xs:element name="action" type="executableType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="executableType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="modifyday" type="modifydayType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="switch" type="switchType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="if" type="ifType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="service" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="executableType">
							<xs:attribute name="time" type="xs:string" use="optional"/>
							<xs:attribute name="timestyle" type="xs:string" use="optional"/>
							<xs:attribute name="name" type="xs:string" use="required"/>
							<xs:attribute name="namestyle" type="xs:string" use="optional"/>
							<xs:attribute name="isdaybefore" type="xs:boolean" use="optional" default="false"/>
							<xs:attribute name="additionalname" type="xs:string" use="optional"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="notice" type="noticeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="text" type="textType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="getClosestDayType">
		<xs:choice>
			<xs:element ref="date" minOccurs="0"/>
		</xs:choice>
		<xs:attribute name="dayofweek" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="понедельник"/>
					<xs:enumeration value="вторник"/>
					<xs:enumeration value="среда"/>
					<xs:enumeration value="четверг"/>
					<xs:enumeration value="пятница"/>
					<xs:enumeration value="суббота"/>
					<xs:enumeration value="воскресенье"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="weekcount" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:element name="date" type="xs:gMonthDay"/>
	<xs:element name="daysfromeaster" type="daysfromeasterType"/>
	<xs:element name="int" type="xs:int"/>
	<xs:complexType name="noticeType">
		<xs:attribute name="time" type="xs:string" use="optional"/>
		<xs:attribute name="timestyle" type="xs:string" use="optional"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="namestyle" type="xs:string" use="optional"/>
		<xs:attribute name="isdaybefore" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="additionalname" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="intOutputType">
		<xs:choice>
			<xs:element ref="daysfromeaster" minOccurs="0"/>
			<xs:element ref="int" minOccurs="0"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="textType">
		<xs:sequence>
			<xs:element name="style" type="styleType"/>
			<xs:element name="text"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="styleType">
		<xs:sequence>
			<xs:element name="red" minOccurs="0" maxOccurs="1"/>
			<xs:element name="bold" minOccurs="0" maxOccurs="1"/>
			<xs:choice minOccurs="0" maxOccurs="1">
				<xs:element name="h1"/>
				<xs:element name="h2"/>
				<xs:element name="h3"/>
				<xs:element name="h4"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ifType">
		<xs:sequence>
			<xs:element name="condition" type="boolValueType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="then" type="executableType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="else" type="executableType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="boolValueType">
		<xs:sequence>
			<xs:element name="equals" type="comparisonType" minOccurs="0"/>
			<xs:element name="more" type="comparisonType" minOccurs="0"/>
			<xs:element name="moreequals" type="comparisonType" minOccurs="0"/>
			<xs:element name="less" type="comparisonType" minOccurs="0"/>
			<xs:element name="lessequals" type="comparisonType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="comparisonType">
		<xs:sequence>
			<xs:element name="op1" type="valueType"/>
			<xs:element name="op2" type="valueType"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Common/вскр_молебен_после_литургии.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Rules/RulesSchema.xsd">
	<!-- если день - вне дней Великого поста, а также Петрова, Успенского и Рождественского-->
	<if>
		<expression>
			<and>
				<or>
					<!-- между Великим и Успенским-->
					<and>
						<more>
							<date/>
							<datebydaysfromeaster>
								<int>7</int>
							</datebydaysfromeaster>
						</more>
						<less>
							<date/>
							<date>--08-14</date>
						</less>
					</and>
					<!-- между Новым годом и Великим постом-->
					<lessequals>
						<date/>
						<datebydaysfromeaster>
							<int>-49</int>
						</datebydaysfromeaster>
					</lessequals>
					<!-- между Успенским постом и Новым годом-->
					<more>
						<date/>
						<date>--08-28</date>
					</more>
				</or>
				<!-- воскресенье-->
				<equals>
					<getdayofweek>
						<date/>
					</getdayofweek>
					<getdayofweek name="воскресенье"/>
				</equals>
			</and>
		</expression>
		<then>
			<!-- Если это первое воскресенье месяца-->
			<if>
				<expression>
					<or>
						<equals>
							<getclosestday dayofweek="воскресенье" weekcount="1">
								<date>--12-31</date>
							</getclosestday>
							<date/>
						</equals>
						<equals>
							<getclosestday dayofweek="воскресенье" weekcount="1">
								<date>--01-31</date>
							</getclosestday>
							<date/>
						</equals>
						<equals>
							<getclosestday dayofweek="воскресенье" weekcount="1">
								<date>--02-28</date>
							</getclosestday>
							<date/>
						</equals>
						<equals>
							<getclosestday dayofweek="воскресенье" weekcount="1">
								<date>--03-31</date>
							</getclosestday>
							<date/>
						</equals>
						<equals>
							<getclosestday dayofweek="воскресенье" weekcount="1">
								<date>--04-30</date>
							</getclosestday>
							<date/>
						</equals>
						<equals>
							<getclosestday dayofweek="воскресенье" weekcount="1">
								<date>--05-31</date>
							</getclosestday>
							<date/>
						</equals>
						<equals>
							<getclosestday dayofweek="воскресенье" weekcount="1">
								<date>--06-30</date>
							</getclosestday>
							<date/>
						</equals>
						<equals>
							<getclosestday dayofweek="воскресенье" weekcount="1">
								<date>--07-31</date>
							</getclosestday>
							<date/>
						</equals>
						<equals>
							<getclosestday dayofweek="воскресенье" weekcount="1">
								<date>--08-31</date>
							</getclosestday>
							<date/>
						</equals>
						<equals>
							<getclosestday dayofweek="воскресенье" weekcount="1">
								<date>--09-30</date>
							</getclosestday>
							<date/>
						</equals>
						<equals>
							<getclosestday dayofweek="воскресенье" weekcount="1">
								<date>--10-31</date>
							</getclosestday>
							<date/>
						</equals>
						<equals>
							<getclosestday dayofweek="воскресенье" weekcount="1">
								<date>--11-30</date>
							</getclosestday>
							<date/>
						</equals>
					</or>
				</expression>
				<then>
					<worship id="moleben">
						<name>Молебен перед иконой Божией Матери "Всецарица". Лития по усопшим.</name>
					</worship>
				</then>
				<else>
					<worship id="moleben">
						<name>Общий молебен. Лития по усопшим.</name>
					</worship>
				</else>
			</if>
		</then>
	</if>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Menology/--03-24.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/%d0%9c%d0%be%d0%bd%d0%b0%d1%81%d1%82%d1%8b%d1%80%d1%8c/Documents/programming/XML/Rules/RulesSchema.xsd">
	<switch>
		<expression>
			<daysfromeaster><date>--03-24</date></daysfromeaster>
		</expression>
		<case>
			<values>
					<int>-43</int>
			</values>
			<action>
				<modifyday daymove="-2" priority="5"/>
				
			</action>
		</case>		
	</switch>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Menology/--01-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Rules/RulesSchema.xsd">
	<if>
		<expression>
			<!--Если воскресенье, то составляем правило особым образом.
				В будущем, надо вынести все в отдельное общее правило CommonRule.-->
			<equals>
				<getdayofweek>
					<date/>
				</getdayofweek>
				<getdayofweek name="воскресенье"/>
			</equals>
		</expression>
		<then>
			<service time="16.00" name="Всенощное бдение." isdaybefore="true"/>
			<service time="23.40" name="Часы 3-й и 6-й." isdaybefore="true"/>
			<service time="00.00" name="Божественная литургия."/>
		</then>
		<else>
			<service time="16.00" name="Вечернее богослужение." isdaybefore="true"/>
			<service time="23.40" name="Часы 3-й и 6-й." isdaybefore="true"/>
			<service time="00.00" name="Божественная литургия."/>
		</else>
	</if>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Menology/Неделя пред Богоявлением.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/%d0%9c%d0%be%d0%bd%d0%b0%d1%81%d1%82%d1%8b%d1%80%d1%8c/Documents/programming/XML/Rules/RulesSchema.xsd">
	<switch>
		<expression>
			<getdayofweek><date>--01-07</date></getdayofweek>
		</expression>
		<case>
			<values>
					<getdayofweek name="понедельник"></getdayofweek>
					<getdayofweek name="воскресенье"></getdayofweek>
					<getdayofweek name="вторник"></getdayofweek>
			</values>
			<action>
				
				
			</action>
		</case>
		<default>
			<modifyday shortname="пред Богоявлением" asaddition="true" usefullname="false">
				<getclosestday dayofweek="воскресенье" weekcount="-1"><date>--01-19</date></getclosestday>
			</modifyday>
		</default>
	</switch>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Menology/--04-06.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Programming/Documentation/TypiconOnline.Documentation/XML/Rules/RulesSchema.xsd">
	<switch>
		<expression>
			<daysfromeaster><date>--04-06</date></daysfromeaster>
		</expression>
		<case>
			<values>
				<int>-19</int>
			</values>
			<action>
				<modifyday daymove="-1"/>
			</action>
		</case>
		<case>
				<values>
					<int>-17</int>
				</values>
			<action>
				<modifyday daymove="-1"/>
			</action>
		</case>
	</switch>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Triodion/-25.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Programming/Documentation/TypiconOnline.Documentation/XML/Rules/RulesSchema.xsd">
	<switch>
		<expression>
			<daysfromeaster><date>--04-07</date></daysfromeaster>
		</expression>
		<case>
			<values>
				<int>-25</int>
			</values>
			<action>
				<modifyday daymove="-2" priority="3"/>
				<service time="17.30" name="9-й час.  Вечерня. Малое повечерие." isdaybefore="true"/>
				<service time="06.00" name="Полунощница. Утреня."></service>
				<service time="08.00" name="Часы. Изобразительны. Вечерня."></service>
			</action>
		</case>
		<default>
			<modifyday daymove="0" priority="3"/>
			<service time="17.30" name="Великое повечерие." isdaybefore="true"/>
			<service time="06.00" name="Полунощница. Утреня. Часы."></service>
			<service time="09.00" name="Литургия Преждеосвященных Даров."></service>
		</default>
	</switch>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Typicon.Migration/Schedule/Common/молебен_после_литургии.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Programming/Documentation/TypiconOnline.Documentation/XML/Rules/RulesSchema.xsd">
	<!-- если день - вне дней Великого поста, а также Петрова, Успенского и Рождественского-->
	<if>
		<expression>
			<or>
				<!-- между Великим и Успенским-->
				<and>
					<more>
						<date/>
						<datebydaysfromeaster>
							<int>7</int>
						</datebydaysfromeaster>
					</more>
					<less>
						<date/>
						<date>--08-14</date>
					</less>
				</and>
				<!-- между Новым годом и Великим постом-->
				<lessequals>
					<date/>
					<datebydaysfromeaster>
						<int>-49</int>
					</datebydaysfromeaster>
				</lessequals>
				<!-- между Успенским постом и Новым годом-->
				<more>
					<date/>
					<date>--08-28</date>
				</more>
			</or>
		</expression>
		<then>
			<!-- Если четверг, добавляем молебен свт. Николаю Чудотворцу-->
			<switch>
				<expression>
					<getdayofweek>
						<date/>
					</getdayofweek>
				</expression>
				<case>
					<values>
						<getdayofweek name="четверг"/>
					</values>
					<action>
						<worship id="moleben">
							<name>Молебен свт. Николаю Чудотворцу.</name>
						</worship>
					</action>
				</case>
				<!-- Если пятница, Молебен перед иконой Божией Матери "Неупиваемая чаша"-->
				<case>
					<values>
						<getdayofweek name="пятница"/>
					</values>
					<action>
						<worship id="moleben">
							<name>Молебен перед иконой Божией Матери "Неупиваемая чаша".</name>
						</worship>
					</action>
				</case>
				<!-- Если суббота и дата позже Недели Всех Святых (63), Молебен перед иконой "Лобзание Иисуса Христа Иудою".-->
				<case>
					<values>
						<getdayofweek name="суббота"/>
					</values>
					<action>
						<if>
							<expression>
								<or>
									<lessequals>
										<date/>
										<datebydaysfromeaster>
											<int>-49</int>
										</datebydaysfromeaster>
									</lessequals>
									<more>
										<date/>
										<datebydaysfromeaster>
											<int>63</int>
										</datebydaysfromeaster>
									</more>
								</or>
							</expression>
							<then>
								<worship id="moleben">
									<name>Молебен перед иконой "Лобзание Иисуса Христа Иудою".</name>
								</worship>
							</then>
						</if>
					</action>
				</case>
				<case>
					<values>
						<getdayofweek name="воскресенье"/>
					</values>
					<action>
						<!-- Если это первое воскресенье месяца-->
						<if>
							<expression>
								<or>
									<equals>
										<getclosestday dayofweek="воскресенье" weekcount="1">
											<date>--12-31</date>
										</getclosestday>
										<date/>
									</equals>
									<equals>
										<getclosestday dayofweek="воскресенье" weekcount="1">
											<date>--01-31</date>
										</getclosestday>
										<date/>
									</equals>
									<equals>
										<getclosestday dayofweek="воскресенье" weekcount="1">
											<date>--02-28</date>
										</getclosestday>
										<date/>
									</equals>
									<equals>
										<getclosestday dayofweek="воскресенье" weekcount="1">
											<date>--03-31</date>
										</getclosestday>
										<date/>
									</equals>
									<equals>
										<getclosestday dayofweek="воскресенье" weekcount="1">
											<date>--04-30</date>
										</getclosestday>
										<date/>
									</equals>
									<equals>
										<getclosestday dayofweek="воскресенье" weekcount="1">
											<date>--05-31</date>
										</getclosestday>
										<date/>
									</equals>
									<equals>
										<getclosestday dayofweek="воскресенье" weekcount="1">
											<date>--06-30</date>
										</getclosestday>
										<date/>
									</equals>
									<equals>
										<getclosestday dayofweek="воскресенье" weekcount="1">
											<date>--07-31</date>
										</getclosestday>
										<date/>
									</equals>
									<equals>
										<getclosestday dayofweek="воскресенье" weekcount="1">
											<date>--08-31</date>
										</getclosestday>
										<date/>
									</equals>
									<equals>
										<getclosestday dayofweek="воскресенье" weekcount="1">
											<date>--09-30</date>
										</getclosestday>
										<date/>
									</equals>
									<equals>
										<getclosestday dayofweek="воскресенье" weekcount="1">
											<date>--10-31</date>
										</getclosestday>
										<date/>
									</equals>
									<equals>
										<getclosestday dayofweek="воскресенье" weekcount="1">
											<date>--11-30</date>
										</getclosestday>
										<date/>
									</equals>
								</or>
							</expression>
							<then>
								<worship id="moleben">
									<name>Молебен перед иконой Божией Матери "Всецарица". Лития по усопшим.</name>
								</worship>
							</then>
							<else>
								<worship id="moleben">
									<name>Общий молебен. Лития по усопшим.</name>
								</worship>
							</else>
						</if>
					</action>
				</case>
			</switch>
		</then>
	</if>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Triodion/-17.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Programming/Documentation/TypiconOnline.Documentation/XML/Rules/RulesSchema.xsd">
	<switch>
		<expression>
			<daysfromeaster><date>--04-07</date></daysfromeaster>
		</expression>
		<case>
			<values>
				<int>-17</int>
			</values>
			<action>
				<modifyday daymove="-2" priority="3"/>
				<service time="16.00" name="Утреня." isdaybefore="true" additionalname="Чтение канона прп. Андрея Критского."/>
				<service time="07.30" name="Полунощница. Часы. Изобразительны."></service>
				<service time="09.00" name="Литургия Преждеосвященных Даров."></service>
			</action>
		</case>
		<case>
			<values>
				<int>-18</int>
			</values>
			<action>
				<modifyday daymove="-2" priority="3"/>
				<service time="16.00" name="Утреня." isdaybefore="true" additionalname="Чтение канона прп. Андрея Критского."/>
				<service time="07.30" name="Полунощница. Часы. Изобразительны."></service>
				<service time="09.00" name="Литургия Преждеосвященных Даров."></service>
			</action>
		</case>
	</switch>
</rule>
