=== irmtim/TypiconOnline.Documentation/XML/DaySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by imtim (imtim company) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="dayservice" type="elementType">
		<xs:annotation>
			<xs:documentation>Текст богослужения на день</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="theotokion" type="ymnosType">
		<xs:annotation>
			<xs:documentation>Текст Богородична из приложений Иромология</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="kanonas" type="kanonasType">
		<xs:annotation>
			<xs:documentation>Текст катавасии канона утрени</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="elementType">
		<xs:sequence>
			<xs:element name="name" type="textType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="mikrosesperinos" type="mikrosesperinosType" minOccurs="0"/>
			<xs:element name="esperinos" type="esperinosType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="apodipno" type="apodipnoType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Повечерие</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="mesoniktiko" type="mesoniktikoType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Полунощница</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="orthros" type="orthrosType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="sixhour" type="sixhourType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="leitourgia" type="leitourgiaType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="apodipnoType">
		<xs:sequence>
			<xs:element name="kanonas" type="kanonasType" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="mesoniktikoType">
		<xs:sequence>
			<xs:element name="kanonas" type="kanonasType" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sixhourType">
		<xs:annotation>
			<xs:documentation>Шестой час в Триоди</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="troparion" type="sticheraType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Тропарь пророчества</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="prokeimeni" type="prokeimeniType" minOccurs="0"/>
			<xs:element name="paroimies">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="paroimia" type="paroimiaType" maxOccurs="3"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="textType">
		<xs:sequence>
			<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="language">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="cs-ru"/>
										<xs:enumeration value="cs-cs"/>
										<xs:enumeration value="ru-ru"/>
										<xs:enumeration value="el-el"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="style" minOccurs="0">
				<xs:complexType>
					<xs:all>
						<xs:element name="bold" type="xs:boolean" minOccurs="0"/>
						<xs:element name="red" type="xs:boolean" minOccurs="0"/>
						<xs:element name="header" minOccurs="0">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="h1"/>
									<xs:enumeration value="h2"/>
									<xs:enumeration value="h3"/>
									<xs:enumeration value="h4"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<!--xs:sequence>
			<xs:element name="cs-ru" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="cs-cs" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ru-ru" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="el-el" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence-->
	</xs:complexType>
	<xs:complexType name="esperinosType">
		<xs:sequence>
			<xs:element name="kekragaria" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="prokeimeni" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="prokeimenon" type="prokeimenonType" maxOccurs="2"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="paroimies" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="paroimia" type="paroimiaType" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="liti" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="aposticha" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="troparion" type="sticheraType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="paroimiesType">
		<xs:sequence>
			<xs:element name="paroimia" type="paroimiaType" minOccurs="1" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="paroimiaType">
		<xs:sequence>
			<xs:element name="bookname" type="textType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="stihos" type="textType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="quote" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="prokeimeniType">
		<xs:sequence>
			<xs:element name="prokeimenon" type="prokeimenonType" minOccurs="1" maxOccurs="2"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="mikrosesperinosType">
		<xs:sequence>
			<xs:element name="kekragaria" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="aposticha" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="troparion" type="sticheraType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="textCollectionType">
		<xs:sequence>
			<xs:element name="stihos" type="textType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="orthrosType">
		<xs:sequence>
			<xs:element name="sed_1kathisma" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="sed_2kathisma" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="sed_3kathisma" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="sed_polyeleos" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="anavathmos" type="sticheraType" minOccurs="0"/>
			<xs:element name="megalynarion" type="textCollectionType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="eclogarion" type="textCollectionType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Псалом избранный</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="prokeimenon" type="prokeimenonType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="evangelion" type="evangelionType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="sticheron_50" type="groupType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="kanones" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="kanonas" type="kanonasType" maxOccurs="3"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ainoi" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="aposticha" type="sticheraType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="kanonesType">
		<xs:sequence>
			<xs:element name="kanonas" type="kanonasType" minOccurs="1" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="leitourgiaType">
		<xs:sequence>
			<xs:element name="makarismi" type="makariosType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>блаженны</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="prokeimenon" type="prokeimenonType" minOccurs="0"/>
			<xs:element name="apostles" type="apostlesType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="alleluia" type="prokeimenonType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="evangelion" type="evangelionType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="kinonik" type="textType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sticheraType">
		<xs:sequence>
			<xs:element name="group" type="groupType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="doxastichon" type="groupType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="theotokion" type="groupType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="groupsType">
		<xs:sequence>
			<xs:element name="group" type="groupType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="groupType">
		<xs:sequence>
			<xs:element name="prosomoion" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="textType">
							<xs:attribute name="self" type="xs:boolean"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="annotation" type="textType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ymnos" type="ymnosType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="ihos" type="xs:byte" use="required"/>
		<xs:attribute name="kind">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="stavros"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ymnisType">
		<xs:sequence>
			<xs:element name="ymnos" type="ymnosType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ymnosType">
		<xs:sequence>
			<xs:element name="annotation" type="textType" minOccurs="0"/>
			<xs:element name="stihos" type="textType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="text" type="textType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="kind">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="theotokion"/>
					<xs:enumeration value="triadiko"/>
					<xs:enumeration value="martyrion"/>
					<xs:enumeration value="ierarhon"/>
					<xs:enumeration value="osion"/>
					<xs:enumeration value="nekrosimo"/>
					<xs:enumeration value="irmos"/>
					<xs:enumeration value="katavasia"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="eclogarionType">
		<xs:sequence>
			<xs:element name="stihos" type="textType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="prokeimenonType">
		<xs:sequence>
			<xs:element name="stihos" type="textType" minOccurs="2" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="ihos" type="xs:byte" use="required"/>
		<xs:attribute name="kind">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="alleluia"/>
					<xs:enumeration value="prokeimenon"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="kanonasType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="name" type="textType" minOccurs="0"/>
			<xs:element name="acrostic" type="textType" minOccurs="0"/>
			<xs:element name="annotation" type="textType" minOccurs="0"/>
			<xs:element name="stihos" type="textType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Припев к тропарям</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="odes" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="odi" type="odiType" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="sedalen" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="kontakion" type="kontakionType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="exapostilarion" type="exapostilarionType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="ihos" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:complexType name="exapostilarionType">
		<xs:sequence>
			<xs:element name="ymnos" type="exapostilarionitemType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="doxastichon" type="exapostilarionitemType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="theotokion" type="exapostilarionitemType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="exapostilarionitemType">
		<xs:sequence>
			<xs:element name="prosomoion" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="textType">
							<xs:attribute name="self" type="xs:boolean"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="annotation" type="textType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="text" type="textType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="odiType">
		<xs:sequence>
			<xs:element name="troparion" type="ymnosType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="number" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:complexType name="kontakionType">
		<xs:sequence>
			<xs:element name="prosomoion" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="textType">
							<xs:attribute name="self" type="xs:boolean"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="annotation" type="textType" minOccurs="0"/>
			<xs:element name="ymnos" type="textType"/>
			<xs:element name="ikos" type="textType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="ihos" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:complexType name="makariosType">
		<xs:sequence>
			<xs:element name="odi" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="number" type="xs:byte" use="required"/>
					<xs:attribute name="count" type="xs:byte" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="ymnis" type="groupType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="apostlesType">
		<xs:sequence>
			<xs:element name="part" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="number" type="xs:int" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="evangelionType">
		<xs:sequence>
			<xs:element name="part" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="bookname" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="Мф"/>
								<xs:enumeration value="Мк"/>
								<xs:enumeration value="Лк"/>
								<xs:enumeration value="Ин"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="number" type="xs:int" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== irmtim/TypiconOnline.Documentation/XML/Books/WeekDayApp/Thursday.xml
<?xml version="1.0" encoding="UTF-8"?>
<dayservice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../DaySchema.xsd">
	<esperinos>
		<prokeimeni>
			<prokeimenon ihos="5">
				<stihos>
					<item language="cs-cs">Б9е, во и4мz твоE спаси1 мz, / и3 въ си1лэ твоeй суди1 ми.</item>
					<item language="cs-ru">Бо́же, во и́мя Твое́ спаси́ мя, / и в си́ле Твое́й суди́ ми.</item>
				</stihos>
				<stihos>
					<item language="cs-cs">Б9е, ўслhши моли1тву мою2, внуши2 глаг0лы ќстъ мои1хъ.</item>
					<item language="cs-ru">Бо́же, услы́ши моли́тву мою́, внуши́ глаго́лы уст мои́х.</item>
				</stihos>
			</prokeimenon>
		</prokeimeni>
	</esperinos>
	<orthros>
		<kanones>
			<kanonas>
				<kontakion ihos="2">
					<ymnos>
						<item language="cs-cs">Твє1рдыz и3 бGовэщ†нныz проповёдатели, вeрхъ ў§нкъ твои1хъ
гDи, пріsлъ є3си2 въ наслаждeніе бlги1хъ твои1хъ и3 пок0й: болBзни
бо џнэхъ, и3 смeрть пріsлъ є3си2 пaче всsкагw всепл0діz, є3ди1не
свёдый сердє1чнаz.</item>
						<item language="cs-ru">Твердыя и боговещанныя проповедатели, / верх апостолов Твоих, Господи, / приял еси в наслаждение благих Твоих и покой: / болезни бо онех и смерть приял еси паче всякаго всеплодия, / Едине, сведый сердечная.</item>
					</ymnos>
				</kontakion>
				<exapostilarion>
					<ymnos>
						<prosomoion>
							<item language="cs-cs">Жєны2 ўслhшите</item>
						</prosomoion>
						<text>
							<item language="cs-cs">Во всю2 подс0лнечную тeкше проповёдасте хrт0во t дв7ы с™0е воплощeніе вои1стинну, t прeлести њбращaюще kзhки, и3 просвэщaюще, и3 вс‰ научaюще трbцу почитaти с™yю, ґпcли сп7сwвы.</item>
						</text>
					</ymnos>
					<theotokion>
						<text>
							<item language="cs-cs">МRjе чистёйшаz, златaz кади1льнице, невмэсти1магw б9ествA пріsтелище бhвшее, въ нeмже nц7ъ бlговоли2, сн7ъ же всели1сz, и3 д¦ъ с™hй њсэни1въ тS nтрокови1це показA бцdу.</item>
						</text>
					</theotokion>
				</exapostilarion>
			</kanonas>
			<kanonas>
				<kontakion ihos="3">
					<ymnos>
						<item language="cs-ru">В Мирех, святе, священнодействитель показался еси, / Христово бо, преподобне, Евангелие исполнив, / положил еси душу твою о людех твоих / и спасл еси неповинныя от смерти. / Сего ради освятился еси, / яко великий таинник Божия благодати.</item>
						<item language="cs-cs">Въ мЂрэхъ, сTMе, сщ7еннодёйствитель показaлсz є3си2, хrт0во бо,
прпdбне, є3ђліе и3сп0лнивъ: положи1лъ є3си2 дyшу твою2 њ лю1дехъ
твои1хъ, и3 сп7слъ є3си2 непови6нныz t смeрти. Сегw2 рaди њсTMи1лсz
є3си2, ћкw вели1кій таи1нникъ б9іz бlгодaти.</item>
					</ymnos>
				</kontakion>
				<exapostilarion>
					<ymnos>
						<prosomoion>
							<item language="cs-cs">Жєны2 ўслhшите</item>
						</prosomoion>
						<text>
							<item language="cs-cs">Вели1каго началопaстырz, и3 їерaрха вси2, предсэдaтелz мmрлmкjйскаго ніколaа хвaлимъ: мнHги бо мyжи сп7сE, непрaведнw ўмрeти и3мyщыz, царю2 kвлsетсz со ґvлaвіемъ во снЁ, рэшS непрaведное и3зречeніе.</item>
						</text>
					</ymnos>
				</exapostilarion>
			</kanonas>
		</kanones>
	</orthros>
	<leitourgia>
		<prokeimenon ihos="8">
			<stihos>
				<item language="cs-cs">Во всю2 зeмлю и3зhде вэщaніе и4хъ, / и3 въ концы2 вселeнныz глаг0лы и4хъ.</item>
				<item language="cs-ru">Во всю землю изыде вещание их / и в концы вселенныя глаголы их.</item>
			</stihos>
			<stihos>
				<item language="cs-cs">Нб7сA повёдаютъ слaву б9ію, творeніе же рукY є3гw2 возвэщaетъ твeрдь.</item>
				<item language="cs-ru">Небеса поведают славу Божию, / творение же руку Его возвещает твердь.</item>
			</stihos>
		</prokeimenon>
		<alleluia ihos="1">
			<stihos>
				<item language="cs-cs">И#сповёдzтъ небесA чудесA тво‰ гDи, и4бо и4стину твою2 въ цRкви с™hхъ.</item>
				<item language="cs-ru">Исповедят небеса чудеса Твоя, Господи, ибо истину Твою в Церкви святых.</item>
			</stihos>
			<stihos>
				<item language="cs-cs">БGъ прославлsемь въ совётэ с™hхъ.</item>
				<item language="cs-ru">Бог прославляем в совете святых.</item>
			</stihos>
		</alleluia>
		<kinonik>
			<item language="cs-cs">Во всю2 зeмлю и3зhде вэщaніе и4хъ и3 въ концы2 вселeнныz глаг0лы и4хъ.</item>
			<item language="cs-ru">Во всю землю изыде вещание их, и в концы вселенныя глаголы их.</item>
		</kinonik>
	</leitourgia>
</dayservice>

=== irmtim/TypiconOnline.Documentation/XML/Books/WeekDayApp/Friday.xml
<?xml version="1.0" encoding="UTF-8"?>
<dayservice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../DaySchema.xsd">
	<esperinos>
		<prokeimeni>
			<prokeimenon ihos="6">
				<stihos>
					<item language="cs-ru">По́мощь моя́ от Го́спода, / сотво́ршаго не́бо и зе́млю.</item>
					<item language="cs-cs">П0мощь моS t гDа / сотв0ршагw нб7о и3 зeмлю.</item>
				</stihos>
				<stihos>
					<item language="cs-cs">Возвед0хъ џчи мои2 въ г0ры, tню1дуже пріи1детъ п0мощь моS.</item>
					<item language="cs-ru">Возведо́х о́чи мои́ в го́ры, отню́дуже прии́дет по́мощь моя́.</item>
				</stihos>
			</prokeimenon>
		</prokeimeni>
		<troparion>
			<group ihos="1">
				<ymnos>
					<text>
						<item language="cs-cs">Сп7си2, гDи, лю1ди тво‰, и3 бlгослови2 достоsніе твоE, побBды
правосл†внымъ хrтіaнwмъ на сопроти6вныz дaруz, и3 твоE сохранsz
кrт0мъ твои1мъ жи1тельство.</item>
						<item language="cs-ru">Спаси, Господи, люди Твоя / и благослови достояние Твое, / победы на сопротивныя даруя / и Твое сохраняя Крестом Твоим жительство.</item>
					</text>
				</ymnos>
			</group>
		</troparion>
	</esperinos>
	<orthros>
		<kanones>
			<kanonas>
				<kontakion ihos="4">
					<ymnos>
						<item language="cs-cs">Вознесhйсz на кrтъ в0лею, тезоимени1тому твоемY н0вому жи1тельству, щедрHты тво‰ дaруй хrтE б9е, возвесели2 нaсъ си1лою твоeю, побBды даS нaмъ на сопостaты, пос0біе и3мyщымъ твоE nрyжіе ми1ра, непобэди1мую побёду.</item>
						<item language="cs-ru">Вознесыйся на Крест волею, / тезоименитому Твоему новому жительству / щедроты Твоя даруй, Христе Боже, / возвесели нас силою Твоею, / победы дая нам на сопостаты, / пособие имущим Твое oружие мира, / непобедимую победу.</item>
					</ymnos>
				</kontakion>
				<exapostilarion>
					<ymnos>
						<text>
							<item language="cs-cs">Кrтъ - храни1тель всеS вселeннаz, кrтъ - красотA цRкве, кrтъ - вёрныхъ ўтверждeніе, кrтъ - ѓгGлwвъ слaва и3 дeмwнwвъ ћзва.</item>
						</text>
					</ymnos>
					<theotokion>
						<text>
							<item language="cs-cs">Ў кrтA предстоsщи, тS безсёменнw р0ждшаz, и3 рыдaющи вопіsше: ўвы2 сладчaйшее чaдо, кaкw зашeлъ є3си2 t џчію моeю; кaкw въ мeртвыхъ вмэни1лсz є3си2;</item>
						</text>
					</theotokion>
				</exapostilarion>
			</kanonas>
		</kanones>
	</orthros>
	<leitourgia>
		<prokeimenon ihos="7">
			<stihos>
				<item language="cs-cs">Возноси1те гDа бGа нaшего, / и3 покланsйтесz подн0жію нHгу є3гw2, ћкw с™о є4сть.</item>
				<item language="cs-ru">Возносите Господа Бога нашего / и поклоняйтеся подножию ногу Его, яко свято есть.</item>
			</stihos>
			<stihos>
				<item language="cs-cs">ГDь воцRи1сz, да гнёваютсz лю1діе.</item>
				<item language="cs-ru">Господь воцарися, да гневаются людие.</item>
			</stihos>
		</prokeimenon>
		<alleluia ihos="1">
			<stihos>
				<item language="cs-cs">Помzни2 с0нмъ тв0й, є3г0же стzжaлъ є3си2 и3спeрва.</item>
				<item language="cs-ru">Помяни сонм Твой, егоже стяжал еси исперва.</item>
			</stihos>
			<stihos>
				<item language="cs-cs">БGъ же цRь нaшъ прeжде вёка, содёла спасeніе посредЁ земли2.</item>
				<item language="cs-ru">Бог же Царь наш прежде века, содела спасение посреде земли.</item>
			</stihos>
		</alleluia>
		<kinonik>
			<item language="cs-cs">Сп7сeніе содёлалъ є3си2 посредЁ земли2, б9е.</item>
			<item language="cs-ru">Спасение соделал еси посреде земли, Боже.</item>
		</kinonik>
	</leitourgia>
</dayservice>

=== irmtim/TypiconOnline.Documentation/XML/Books/WeekDayApp/Tuesday.xml
<?xml version="1.0" encoding="UTF-8"?>
<dayservice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../DaySchema.xsd">
	<esperinos>
		<prokeimeni>
			<prokeimenon ihos="4">
				<stihos>
					<item language="cs-cs">ГDь ўслhшитъ мS, / внегдA воззвaти ми2 къ немY.</item>
					<item language="cs-ru">Госпо́дь услы́шит мя, / внегда́ воззва́ти ми к Нему́.</item>
				</stihos>
				<stihos>
					<item language="cs-cs">ВнегдA призвaти ми2, ўслhша мS бGъ прaвды моеS.</item>
					<item language="cs-ru">Внегда́ призва́ти ми, услы́ша мя Бог пра́вды моея́.</item>
				</stihos>
			</prokeimenon>
		</prokeimeni>
		<troparion>
			<group ihos="2">
				<ymnos>
					<text>
						<item language="cs-cs">Пaмzть првdнагw съ похвалaми, тебё же довлёетъ свидётельство гDне, п®тeче: показaлъ бо сz є3си2 вои1стинну и прbр0кwвъ чcтнёйшій, ћкw и3 въ струsхъ кrти1ти спод0билсz є3си2 проповёданнаго. Тёмже за и4стину пострадaвъ рaдуzсz, бlговэсти1лъ є3си2 и3 сyщымъ во ѓдэ бGа ћвльшагосz пл0тію, взeмлющаго грёхъ мjра, и3 подаю1щаго нaмъ вeлію млcть.</item>
						<item language="cs-ru">Память праведнаго с похвалами, / тебе же довлеет свидетельство Господне, Предтече: / показал бо ся еси воистинну и пророков честнейший, / яко и в струях крестити сподобился еси Проповеданнаго. / Темже за истину пострадав радуяся, / благовестил еси и сущим во аде Бога, явльшагося плотию, / вземлющаго грех мира / и подающаго нам велию милость.</item>
					</text>
				</ymnos>
			</group>
		</troparion>
	</esperinos>
	<orthros>
		<kanones>
			<kanonas>
				<kontakion ihos="2">
					<ymnos>
						<item language="cs-ru">Пророче Божий и Предтече благодати, / главу твою, яко шипок священнейший от земли обретше, / исцеления всегда приемлем, / ибо паки, якоже прежде, / в мире проповедуеши покаяние.</item>
						<item language="cs-cs">Прbр0че б9ій, и3 п®тeче бlгодaти, главY твою2 ћкw ши1покъ сщ7eннэйшій t земли2 њбрётше, и3сцэлє1ніz всегдA пріeмлемъ: и4бо пaки ћкоже прeжде въ мjрэ проповёдуеши покаsніе.</item>
					</ymnos>
				</kontakion>
				<exapostilarion>
					<ymnos>
						<text>
							<item language="cs-cs">П®тeчу їwaнна, и3 кrти1телz сп7сова, во прbр0цэхъ прbр0ка, и3 пустhни воспитaніе, є3лісавeтино рождeніе восхвaлимъ вси2.</item>
						</text>
					</ymnos>
					<theotokion>
						<text>
							<item language="cs-cs">Слaдость ѓгGлwвъ, скорбsщихъ рaдость, хrтіaнъ предстaтельница дв7о м™и гDнz, заступи2 нaсъ, и3 и3збaви вёчныхъ мyкъ.</item>
						</text>
					</theotokion>
				</exapostilarion>
			</kanonas>
		</kanones>
	</orthros>
	<leitourgia>
		<prokeimenon ihos="7">
			<stihos>
				<item language="cs-cs">Возвесели1тсz прaведникъ њ гDэ, / и3 ўповaетъ на него2.</item>
				<item language="cs-ru">Возвеселится праведник о Господе, / и уповает на Него.</item>
			</stihos>
			<stihos>
				<item language="cs-cs">Ўслhши б9е глaсъ м0й, внегдA моли1ти ми сz къ тебЁ.</item>
				<item language="cs-ru">Услыши Боже глас мой, внегда молити ми ся к Тебе.</item>
			</stihos>
		</prokeimenon>
		<alleluia ihos="4">
			<stihos>
				<item language="cs-cs">Прaведникъ ћкw фjніxъ процвэтeтъ, ћкw кeдръ и4же въ лівaнэ ўмн0житсz.</item>
				<item language="cs-ru">Праведник яко финикс процветет, яко кедр, иже в Ливане, умножится.</item>
			</stihos>
			<stihos>
				<item language="cs-cs">Насаждeни въ домY гDни, во дв0рэхъ бGа нaшегw процвэтyтъ.</item>
				<item language="cs-ru">Насаждени в дому Господни, во дворех Бога нашего процветут.</item>
			</stihos>
		</alleluia>
		<kinonik>
			<item language="cs-cs">Въ пaмzть вёчную бyдетъ првdникъ, t слyха ѕлA не ўбои1тсz.</item>
			<item language="cs-ru">В память вечную будет праведник, от слуха зла не убоится.</item>
		</kinonik>
	</leitourgia>
</dayservice>
