=== irmtim/TypiconOnline.Documentation/XML/DaySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by imtim (imtim company) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="dayservice" type="elementType">
		<xs:annotation>
			<xs:documentation>Текст богослужения на день</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="theotokion" type="ymnosType">
		<xs:annotation>
			<xs:documentation>Текст Богородична из приложений Иромология</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="kanonas" type="kanonasType">
		<xs:annotation>
			<xs:documentation>Текст катавасии канона утрени</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="elementType">
		<xs:sequence>
			<xs:element name="name" type="textType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="mikrosesperinos" type="mikrosesperinosType" minOccurs="0"/>
			<xs:element name="esperinos" type="esperinosType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="apodipno" type="apodipnoType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Повечерие</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="mesoniktiko" type="mesoniktikoType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Полунощница</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="orthros" type="orthrosType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="sixhour" type="sixhourType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="leitourgia" type="leitourgiaType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="apodipnoType">
		<xs:sequence>
			<xs:element name="kanonas" type="kanonasType" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="mesoniktikoType">
		<xs:sequence>
			<xs:element name="kanonas" type="kanonasType" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sixhourType">
		<xs:annotation>
			<xs:documentation>Шестой час в Триоди</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="troparion" type="sticheraType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Тропарь пророчества</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="prokeimeni" type="prokeimeniType" minOccurs="0"/>
			<xs:element name="paroimies">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="paroimia" type="paroimiaType" maxOccurs="3"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="textType">
		<xs:sequence>
			<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="language">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="cs-ru"/>
										<xs:enumeration value="cs-cs"/>
										<xs:enumeration value="ru-ru"/>
										<xs:enumeration value="el-el"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="style" minOccurs="0">
				<xs:complexType>
					<xs:all>
						<xs:element name="bold" type="xs:boolean" minOccurs="0"/>
						<xs:element name="red" type="xs:boolean" minOccurs="0"/>
						<xs:element name="header" minOccurs="0">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="h1"/>
									<xs:enumeration value="h2"/>
									<xs:enumeration value="h3"/>
									<xs:enumeration value="h4"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<!--xs:sequence>
			<xs:element name="cs-ru" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="cs-cs" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ru-ru" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="el-el" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence-->
	</xs:complexType>
	<xs:complexType name="esperinosType">
		<xs:sequence>
			<xs:element name="kekragaria" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="prokeimeni" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="prokeimenon" type="prokeimenonType" maxOccurs="2"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="paroimies" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="paroimia" type="paroimiaType" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="liti" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="aposticha" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="troparion" type="sticheraType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="paroimiesType">
		<xs:sequence>
			<xs:element name="paroimia" type="paroimiaType" minOccurs="1" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="paroimiaType">
		<xs:sequence>
			<xs:element name="bookname" type="textType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="stihos" type="textType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="quote" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="prokeimeniType">
		<xs:sequence>
			<xs:element name="prokeimenon" type="prokeimenonType" minOccurs="1" maxOccurs="2"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="mikrosesperinosType">
		<xs:sequence>
			<xs:element name="kekragaria" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="aposticha" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="troparion" type="sticheraType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="textCollectionType">
		<xs:sequence>
			<xs:element name="stihos" type="textType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="orthrosType">
		<xs:sequence>
			<xs:element name="sed_1kathisma" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="sed_2kathisma" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="sed_3kathisma" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="sed_polyeleos" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="anavathmos" type="sticheraType" minOccurs="0"/>
			<xs:element name="megalynarion" type="textCollectionType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="eclogarion" type="textCollectionType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Псалом избранный</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="prokeimenon" type="prokeimenonType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="evangelion" type="evangelionType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="sticheron_50" type="groupType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="kanones" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="kanonas" type="kanonasType" maxOccurs="3"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ainoi" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="aposticha" type="sticheraType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="kanonesType">
		<xs:sequence>
			<xs:element name="kanonas" type="kanonasType" minOccurs="1" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="leitourgiaType">
		<xs:sequence>
			<xs:element name="makarismi" type="makariosType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>блаженны</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="prokeimenon" type="prokeimenonType" minOccurs="0"/>
			<xs:element name="apostles" type="apostlesType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="alleluia" type="prokeimenonType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="evangelion" type="evangelionType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="kinonik" type="textType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sticheraType">
		<xs:sequence>
			<xs:element name="group" type="groupType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="doxastichon" type="groupType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="theotokion" type="groupType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="groupsType">
		<xs:sequence>
			<xs:element name="group" type="groupType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="groupType">
		<xs:sequence>
			<xs:element name="prosomoion" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="textType">
							<xs:attribute name="self" type="xs:boolean"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="annotation" type="textType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ymnos" type="ymnosType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="ihos" type="xs:byte" use="required"/>
		<xs:attribute name="kind">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="stavros"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ymnisType">
		<xs:sequence>
			<xs:element name="ymnos" type="ymnosType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ymnosType">
		<xs:sequence>
			<xs:element name="annotation" type="textType" minOccurs="0"/>
			<xs:element name="stihos" type="textType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="text" type="textType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="kind">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="theotokion"/>
					<xs:enumeration value="triadiko"/>
					<xs:enumeration value="martyrion"/>
					<xs:enumeration value="ierarhon"/>
					<xs:enumeration value="osion"/>
					<xs:enumeration value="nekrosimo"/>
					<xs:enumeration value="irmos"/>
					<xs:enumeration value="katavasia"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="eclogarionType">
		<xs:sequence>
			<xs:element name="stihos" type="textType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="prokeimenonType">
		<xs:sequence>
			<xs:element name="stihos" type="textType" minOccurs="2" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="ihos" type="xs:byte" use="required"/>
		<xs:attribute name="kind">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="alleluia"/>
					<xs:enumeration value="prokeimenon"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="kanonasType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="name" type="textType" minOccurs="0"/>
			<xs:element name="acrostic" type="textType" minOccurs="0"/>
			<xs:element name="annotation" type="textType" minOccurs="0"/>
			<xs:element name="stihos" type="textType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Припев к тропарям</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="odes" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="odi" type="odiType" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="sedalen" type="sticheraType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="kontakion" type="kontakionType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="exapostilarion" type="exapostilarionType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="ihos" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:complexType name="exapostilarionType">
		<xs:sequence>
			<xs:element name="ymnos" type="exapostilarionitemType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="doxastichon" type="exapostilarionitemType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="theotokion" type="exapostilarionitemType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="exapostilarionitemType">
		<xs:sequence>
			<xs:element name="prosomoion" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="textType">
							<xs:attribute name="self" type="xs:boolean"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="annotation" type="textType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="text" type="textType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="odiType">
		<xs:sequence>
			<xs:element name="troparion" type="ymnosType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="number" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:complexType name="kontakionType">
		<xs:sequence>
			<xs:element name="prosomoion" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="textType">
							<xs:attribute name="self" type="xs:boolean"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="annotation" type="textType" minOccurs="0"/>
			<xs:element name="ymnos" type="textType"/>
			<xs:element name="ikos" type="textType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="ihos" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:complexType name="makariosType">
		<xs:sequence>
			<xs:element name="odi" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="number" type="xs:byte" use="required"/>
					<xs:attribute name="count" type="xs:byte" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="ymnis" type="groupType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="apostlesType">
		<xs:sequence>
			<xs:element name="part" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="number" type="xs:int" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="evangelionType">
		<xs:sequence>
			<xs:element name="part" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="bookname" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="Мф"/>
								<xs:enumeration value="Мк"/>
								<xs:enumeration value="Лк"/>
								<xs:enumeration value="Ин"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="number" type="xs:int" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== irmtim/TypiconOnline.Documentation/XML/Books/WeekDayApp/Saturday.xml
<?xml version="1.0" encoding="UTF-8"?>
<dayservice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../DaySchema.xsd">
	<esperinos>
		<prokeimeni>
			<prokeimenon ihos="7">
				<stihos>
					<item language="cs-ru">Бо́же, Засту́пник мой еси́ Ты, / и ми́лость Твоя́ предвари́т мя.</item>
					<item language="cs-cs">Б9е, застyпникъ м0й є3си2 ты2, / и3 ми1лость твоS предвари1тъ мS.</item>
				</stihos>
				<stihos>
					<item language="cs-ru">Изми́ мя от враг мои́х, Бо́же, и от востаю́щих на мя изба́ви мя.</item>
					<item language="cs-cs">И#зми1 мz t вр†гъ мои1хъ б9е, и3 t востаю1щихъ на мS и3збaви мS.</item>
				</stihos>
			</prokeimenon>
		</prokeimeni>
		<troparion>
			<group ihos="2">
				<ymnos>
					<text>
						<item language="cs-cs">Ґпcли, м§нцы и3 прbр0цы, сTMи1теліе, прпdбніи и3 првdніи, д0брэ п0двигъ соверши1вшіи, и3 вёру соблю1дшіи, дерзновeніе и3мyще ко сп7су, њ нaсъ того2 ћкw бlга моли1те сп7сти1сz, м0лимсz, душaмъ нaшымъ.</item>
					</text>
				</ymnos>
				<ymnos kind="nekrosimo">
					<text>
						<item language="cs-cs">Помzни2 гDи, ћкw бlгъ, рабы6 тво‰, и3 є3ли6ка въ житіи2 согрэши1ша, прости2: никт0же бо безгрёшенъ, т0кмw ты2 могjй и3 престaвлєннымъ дaти пок0й.</item>
					</text>
				</ymnos>
			</group>
		</troparion>
	</esperinos>
	<orthros/>
	<leitourgia>
		<prokeimenon ihos="8">
			<stihos>
				<item language="cs-cs">Весели1тесz њ гDэ, / и3 рaдуйтесz прaведніи.</item>
				<item language="cs-ru">Веселитеся о Господе, / и радуйтеся праведнии.</item>
			</stihos>
			<stihos>
				<item language="cs-cs">Бlжeни, и4хже њстaвишасz беззакHніz, и3 и4хже прикрhшасz грэси2.</item>
				<item language="cs-ru">Блажени, ихже оставишася беззакония и ихже прикрышася греси.</item>
			</stihos>
		</prokeimenon>
		<prokeimenon ihos="6" kind="nekrosimo">
			<stihos>
				<item language="cs-cs">Дyшы и4хъ / во бlги1хъ водворsтсz.</item>
				<item language="cs-ru">Души их во благих водворятся.</item>
			</stihos>
		</prokeimenon>
		<alleluia ihos="4">
			<stihos>
				<item language="cs-cs">Воззвaша прaведніи, и3 гDь ўслhша и5хъ, и3 t всёхъ скорбeй и4хъ и3збaви и5хъ.</item>
				<item language="cs-ru">Воззваша праведнии, и Господь услыша их, и от всех скорбей их избави их.</item>
			</stihos>
			<stihos>
				<item language="cs-cs">Мн0ги скHрби прaвєднымъ, и3 t всёхъ и4хъ и3збaвитъ | гDь.</item>
				<item language="cs-ru">Многи скорби праведным, и от всех их избавит я Господь.</item>
			</stihos>
		</alleluia>
		<alleluia ihos="4" kind="nekrosimo">
			<stihos>
				<item language="cs-cs">Бlжeни, ±же и3збрaлъ и3 пріsлъ є3си2 гDи.</item>
				<item language="cs-ru">Блажени, яже избрал и приял еси, Господи.</item>
			</stihos>
			<stihos>
				<item language="cs-cs">И# пaмzть и4хъ въ р0дъ и3 р0дъ.</item>
				<item language="cs-ru">И память их в род и род.</item>
			</stihos>
		</alleluia>
		<kinonik>
			<item language="cs-cs">Рaдуйтесz прaведніи њ гDэ, прaвымъ подобaетъ похвалA.</item>
			<item language="cs-ru">Радуйтеся, праведнии, о Господе, правым подобает похвала.</item>
		</kinonik>
		<kinonik kind="nekrosimo">
			<item language="cs-cs">Бlжeни ±же и3збрaлъ и3 пріsлъ є3си2 гDи, и3 пaмzть и4хъ въ р0дъ и3 р0дъ.</item>
			<item language="cs-ru">Блажени, яже избрал и приял еси, Господи, и память их в род и род.</item>
		</kinonik>
	</leitourgia>
</dayservice>

=== irmtim/TypiconOnline.Documentation/XML/Books/WeekDayApp/Monday.xml
<?xml version="1.0" encoding="UTF-8"?>
<dayservice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../DaySchema.xsd">
	<esperinos>
		<prokeimeni>
			<prokeimenon ihos="8">
				<stihos>
					<item language="cs-ru">Се ны́не благослови́те Го́спода / вси раби́ Госпо́дни.</item>
					<item language="cs-cs">СE нhнэ бlгослови1те гDа / вси2 раби2 гDни.</item>
				</stihos>
				<stihos>
					<item language="cs-ru">Стоя́щии в хра́ме Госпо́дни, во дво́рех до́му Бо́га на́шего.</item>
					<item language="cs-cs">Стоsщіи во хрaмэ гDни, во дв0рэхъ д0му бGа нaшегw.</item>
				</stihos>
			</prokeimenon>
		</prokeimeni>
		<troparion>
			<group ihos="4">
				<ymnos>
					<text>
						<item language="cs-cs">Нбcныхъ в0инствъ ґрхістрати1зи, м0лимъ вaсъ при1снw мы2 недост0йніи, да вaшими мlтвами њградитE нaсъ кр0вомъ кри1лъ невещeственныz вaшеz слaвы, сохранsюще нaсъ припaдающихъ прилёжнw, и3 вопію1щихъ: t бёдъ и3збaвите нaсъ, ћкw
чинонач†льницы вhшнихъ си1лъ.</item>
						<item language="cs-ru">Небесных воинств Архистратизи, / молим вас присно мы, недостойнии, / да вашими молитвами оградите нас / кровом крил невещественныя вашея славы, / сохраняюще нас, припадающих прилежно и вопиющих: / от бед избавите нас, / яко чиноначальницы вышних Сил.</item>
					</text>
				</ymnos>
			</group>
		</troparion>
	</esperinos>
	<orthros>
		<kanones>
			<kanonas>
				<kontakion ihos="2">
					<ymnos>
						<item language="cs-ru">Архистратизи Божии, / служителие Божественныя славы, / Ангелов начальницы и человеков наставницы, / полезное нам просите и велию милость, / яко Безплотных Архистратизи.</item>
						<item language="cs-cs">Ґрхістрати1зи б9іи, служи1теліе бжcтвенныz слaвы, ѓгGлwвъ нач†льницы, и3 человёкwмъ наст†вницы, полeзное нaмъ проси1те, и3 вeлію млcть, ћкw безпл0тныхъ ґрхістрати1зи.</item>
					</ymnos>
				</kontakion>
				<exapostilarion>
					<ymnos>
						<text>
							<item language="cs-cs">Нeбо ѕвэздaми ўкраси1вый ћкw бGъ, и3 твои1ми ѓгGлы всю2 зeмлю просвэти1вый, содётелю всёхъ, пою1щыz тS сп7сaй.</item>
						</text>
					</ymnos>
					<theotokion>
						<text>
							<item language="cs-cs">Слaдость ѓгGлwвъ, скорбsщихъ рaдость, хrтіaнъ предстaтельница дв7о м™и гDнz, заступи2 нaсъ, и3 и3збaви вёчныхъ мyкъ.</item>
						</text>
					</theotokion>
				</exapostilarion>
			</kanonas>
		</kanones>
	</orthros>
	<leitourgia>
		<prokeimenon ihos="4">
			<stihos>
				<item language="cs-cs">Творsй ѓгGлы своS д¦и, / и3 слуги6 своS плaмень џгненный. </item>
				<item language="cs-ru">Творяй Ангелы Своя духи / и слуги Своя пламень огненный.</item>
			</stihos>
			<stihos>
				<item language="cs-cs">Благослови2 душE моS гDа, гDи б9е м0й, возвели1чилсz є3си2 ѕэлw2.</item>
				<item language="cs-ru">Благослови, душе моя, Господа, Господи Боже мой, возвеличился еси зело.</item>
			</stihos>
		</prokeimenon>
		<alleluia ihos="5">
			<stihos>
				<item language="cs-cs">Хвали1те гDа вси2 ѓгGли є3гw2, хвали1те є3го2 вс‰ си6лы є3гw2. </item>
				<item language="cs-ru">Хвалите Господа, вси Ангели Его, хвалите Его, вся силы Его.</item>
			</stihos>
			<stihos>
				<item language="cs-cs">Ћкw т0й речE, и3 бhша: т0й повелЁ, и3 создaшасz.</item>
				<item language="cs-ru">Яко Той рече, и быша; Той повеле, и создашася.</item>
			</stihos>
		</alleluia>
		<kinonik>
			<item language="cs-ru">Творяй Ангелы Своя духи, и слуги Своя пламень огненный.</item>
			<item language="cs-cs">Творsй ѓгGлы сво‰ д¦и, и3 слуги6 сво‰ плaмень џгненный.</item>
		</kinonik>
	</leitourgia>
</dayservice>
