=== irmtim/TypiconOnline.Documentation/XML/Rules/RulesModSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by imtim (imtim company) -->
<!--W3C Schema generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rule" type="executableType"/>
	<xs:complexType name="switchType">
		<xs:sequence>
			<xs:element name="expression" type="valueType"/>
			<xs:element name="case" type="caseType" maxOccurs="unbounded"/>
			<xs:element name="default" type="executableType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="daysfromeasterType">
		<xs:choice>
			<xs:element ref="date" minOccurs="0"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="datebydaysfromeaster" type="intOutputType"/>
	<xs:element name="getclosestday" type="getClosestDayType"/>
	<xs:complexType name="modifydayType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="shortname" type="textType" minOccurs="0"/>
			<xs:element ref="getclosestday" minOccurs="0"/>
			<xs:element ref="date" minOccurs="0"/>
			<xs:element ref="datebydaysfromeaster" minOccurs="0"/>
			<xs:element name="modifyreplacedday" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="modifydayType">
							<xs:attribute name="kind" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="menology"/>
										<xs:enumeration value="triodion"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="signname" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="пасха"/>
					<xs:enumeration value="светлая_седмица"/>
					<xs:enumeration value="бдение_лития"/>
					<xs:enumeration value="бдение"/>
					<xs:enumeration value="полиелей"/>
					<xs:enumeration value="воскресный_день"/>
					<xs:enumeration value="алиллуиа"/>
					<xs:enumeration value="лпд"/>
					<xs:enumeration value="поминовение_усопших"/>
					<xs:enumeration value="поминовение_усопших_пост"/>
					<xs:enumeration value="славословие"/>
					<xs:enumeration value="шестеричная"/>
					<xs:enumeration value="без_знака"/>
					<xs:enumeration value="12"/>
					<xs:enumeration value="страстная_седмица"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="daymove" type="xs:byte" use="optional"/>
		<xs:attribute name="priority" type="xs:int" use="optional"/>
		<xs:attribute name="asaddition" type="xs:boolean"/>
		<xs:attribute name="islastname" type="xs:boolean"/>
		<xs:attribute name="usefullname" type="xs:boolean"/>
		<xs:attribute name="excludeitem" type="xs:int"/>
		<xs:attribute name="includeitem" type="xs:int"/>
		<xs:attribute name="iscelebrating" type="xs:boolean"/>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="asadditionmode">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="none"/>
					<xs:enumeration value="append"/>
					<xs:enumeration value="rewrite"/>
					<xs:enumeration value="remove"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="valueType">
		<xs:choice>
			<xs:element name="daysfromeaster" type="daysfromeasterType" minOccurs="0"/>
			<xs:element ref="date" minOccurs="0"/>
			<xs:element name="int" type="xs:int" minOccurs="0"/>
			<xs:element name="getclosestday" type="getClosestDayType" minOccurs="0"/>
			<xs:element name="getdayofweek" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="getdayofweekType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="getdayofweekType">
		<xs:sequence>
			<xs:element ref="date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="getclosestday" type="getClosestDayType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="понедельник"/>
					<xs:enumeration value="вторник"/>
					<xs:enumeration value="среда"/>
					<xs:enumeration value="четверг"/>
					<xs:enumeration value="пятница"/>
					<xs:enumeration value="суббота"/>
					<xs:enumeration value="воскресенье"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="valuesType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="daysfromeaster" type="daysfromeasterType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="int" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="getclosestday" type="getClosestDayType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="getdayofweek" type="getdayofweekType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="datebydaysfromeaster" type="intOutputType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="caseType">
		<xs:sequence>
			<xs:element name="values" type="valuesType"/>
			<xs:element name="action" type="executableType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="executableType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="modifyday" type="modifydayType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="switch" type="switchType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="if" type="ifType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="commonrule" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="textType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="bold" type="xs:boolean" use="optional"/>
				<xs:attribute name="red" type="xs:boolean" use="optional"/>
				<xs:attribute name="italic" type="xs:boolean" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="ifType">
		<xs:sequence>
			<xs:element name="expression" type="booleanType"/>
			<xs:element name="then" type="executableType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="else" type="executableType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="booleanType">
		<xs:choice>
			<xs:group ref="booleanGroup"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="logicalType">
		<xs:sequence maxOccurs="unbounded">
			<xs:group ref="booleanGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:group name="booleanGroup">
		<xs:sequence>
			<xs:element name="equals" type="valuesType" minOccurs="0"/>
			<xs:element name="more" type="valuesType" minOccurs="0"/>
			<xs:element name="moreequals" type="valuesType" minOccurs="0"/>
			<xs:element name="less" type="valuesType" minOccurs="0"/>
			<xs:element name="lessequals" type="valuesType" minOccurs="0"/>
			<xs:element name="and" type="logicalType" minOccurs="0"/>
			<xs:element name="or" type="logicalType" minOccurs="0"/>
			<xs:element name="iscelebrating" minOccurs="0"/>
			<xs:element name="istwosaints" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="getClosestDayType">
		<xs:choice>
			<xs:element ref="date" minOccurs="0"/>
		</xs:choice>
		<xs:attribute name="dayofweek" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="понедельник"/>
					<xs:enumeration value="вторник"/>
					<xs:enumeration value="среда"/>
					<xs:enumeration value="четверг"/>
					<xs:enumeration value="пятница"/>
					<xs:enumeration value="суббота"/>
					<xs:enumeration value="воскресенье"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="weekcount" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:element name="date" type="xs:string"/>
	<!--xs:element name="date" type="xs:gMonthDay"/-->
	<xs:element name="daysfromeaster" type="daysfromeasterType"/>
	<xs:element name="int" type="xs:int"/>
	<xs:element name="equals">
		<xs:complexType>
			<xs:sequence/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="intOutputType">
		<xs:choice>
			<xs:element ref="daysfromeaster" minOccurs="0"/>
			<xs:element ref="int" minOccurs="0"/>
		</xs:choice>
	</xs:complexType>
</xs:schema>

=== irmtim/TypiconOnline.Documentation/XML/Typicon.Migration/Calendar/MenologyAndMovable/--02-21.mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Programming/Documentation/TypiconOnline.Documentation/XML/Rules/RulesModSchema.xsd">
	<switch>
		<expression>
			<daysfromeaster>
				<date>--02-15</date>
			</daysfromeaster>
		</expression>
		<case>
			<values>
				<int>-48</int>
				<int>-49</int>
				<int>-50</int>
				<int>-51</int>
				<int>-52</int>
				<int>-53</int>
				<int>-54</int>
				<int>-55</int>
				<int>-56</int>
				<int>-57</int>
				<int>-58</int>
				<int>-59</int>
				<int>-61</int>
				<int>-62</int>
				<int>-63</int>
			</values>
			<action>
				<!-- Фильтрация – Исключаем попразднество -->
				<modifyday iscelebrating="false" daymove="0"/>
			</action>
		</case>
		<case>
			<values>
				<int>-60</int>
			</values>
			<action>
				<!-- Не служим – Отдание праздника -->
				<modifyday priority="6" daymove="0"/>
			</action>
		</case>
	</switch>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Typicon.Migration/Calendar/MenologyAndMovable/Димитриевская родительская суббота. Поминовение усопших.mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Programming/Documentation/TypiconOnline.Documentation/XML/Rules/RulesModSchema.xsd">
	<switch>
		<expression>
			<getclosestday dayofweek="суббота" weekcount="-1">
				<date>--11-08</date>
			</getclosestday>
		</expression>
		<case>
			<values>
				<date>--11-04</date>
			</values>
			<action>
				<modifyday asaddition="true">
					<getclosestday dayofweek="суббота" weekcount="-2">
						<date>--11-08</date>
					</getclosestday>
				</modifyday>
			</action>
		</case>
		<default>
			<modifyday asaddition="true">
				<getclosestday dayofweek="суббота" weekcount="-1">
					<date>--11-08</date>
				</getclosestday>
			</modifyday>
		</default>
	</switch>
</rule>
