=== irmtim/TypiconOnline.Documentation/XML/Rules/RulesModSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by imtim (imtim company) -->
<!--W3C Schema generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rule" type="executableType"/>
	<xs:complexType name="switchType">
		<xs:sequence>
			<xs:element name="expression" type="valueType"/>
			<xs:element name="case" type="caseType" maxOccurs="unbounded"/>
			<xs:element name="default" type="executableType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="daysfromeasterType">
		<xs:choice>
			<xs:element ref="date" minOccurs="0"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="datebydaysfromeaster" type="intOutputType"/>
	<xs:element name="getclosestday" type="getClosestDayType"/>
	<xs:complexType name="modifydayType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="shortname" type="textType" minOccurs="0"/>
			<xs:element ref="getclosestday" minOccurs="0"/>
			<xs:element ref="date" minOccurs="0"/>
			<xs:element ref="datebydaysfromeaster" minOccurs="0"/>
			<xs:element name="modifyreplacedday" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="modifydayType">
							<xs:attribute name="kind" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="menology"/>
										<xs:enumeration value="triodion"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="signname" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="пасха"/>
					<xs:enumeration value="светлая_седмица"/>
					<xs:enumeration value="бдение_лития"/>
					<xs:enumeration value="бдение"/>
					<xs:enumeration value="полиелей"/>
					<xs:enumeration value="воскресный_день"/>
					<xs:enumeration value="алиллуиа"/>
					<xs:enumeration value="лпд"/>
					<xs:enumeration value="поминовение_усопших"/>
					<xs:enumeration value="поминовение_усопших_пост"/>
					<xs:enumeration value="славословие"/>
					<xs:enumeration value="шестеричная"/>
					<xs:enumeration value="без_знака"/>
					<xs:enumeration value="12"/>
					<xs:enumeration value="страстная_седмица"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="daymove" type="xs:byte" use="optional"/>
		<xs:attribute name="priority" type="xs:int" use="optional"/>
		<xs:attribute name="asaddition" type="xs:boolean"/>
		<xs:attribute name="islastname" type="xs:boolean"/>
		<xs:attribute name="usefullname" type="xs:boolean"/>
		<xs:attribute name="excludeitem" type="xs:int"/>
		<xs:attribute name="includeitem" type="xs:int"/>
		<xs:attribute name="iscelebrating" type="xs:boolean"/>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="asadditionmode">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="none"/>
					<xs:enumeration value="append"/>
					<xs:enumeration value="rewrite"/>
					<xs:enumeration value="remove"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="valueType">
		<xs:choice>
			<xs:element name="daysfromeaster" type="daysfromeasterType" minOccurs="0"/>
			<xs:element ref="date" minOccurs="0"/>
			<xs:element name="int" type="xs:int" minOccurs="0"/>
			<xs:element name="getclosestday" type="getClosestDayType" minOccurs="0"/>
			<xs:element name="getdayofweek" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="getdayofweekType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="getdayofweekType">
		<xs:sequence>
			<xs:element ref="date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="getclosestday" type="getClosestDayType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="понедельник"/>
					<xs:enumeration value="вторник"/>
					<xs:enumeration value="среда"/>
					<xs:enumeration value="четверг"/>
					<xs:enumeration value="пятница"/>
					<xs:enumeration value="суббота"/>
					<xs:enumeration value="воскресенье"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="valuesType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="daysfromeaster" type="daysfromeasterType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="int" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="getclosestday" type="getClosestDayType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="getdayofweek" type="getdayofweekType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="datebydaysfromeaster" type="intOutputType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="caseType">
		<xs:sequence>
			<xs:element name="values" type="valuesType"/>
			<xs:element name="action" type="executableType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="executableType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="modifyday" type="modifydayType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="switch" type="switchType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="if" type="ifType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="commonrule" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="textType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="bold" type="xs:boolean" use="optional"/>
				<xs:attribute name="red" type="xs:boolean" use="optional"/>
				<xs:attribute name="italic" type="xs:boolean" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="ifType">
		<xs:sequence>
			<xs:element name="expression" type="booleanType"/>
			<xs:element name="then" type="executableType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="else" type="executableType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="booleanType">
		<xs:choice>
			<xs:group ref="booleanGroup"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="logicalType">
		<xs:sequence maxOccurs="unbounded">
			<xs:group ref="booleanGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:group name="booleanGroup">
		<xs:sequence>
			<xs:element name="equals" type="valuesType" minOccurs="0"/>
			<xs:element name="more" type="valuesType" minOccurs="0"/>
			<xs:element name="moreequals" type="valuesType" minOccurs="0"/>
			<xs:element name="less" type="valuesType" minOccurs="0"/>
			<xs:element name="lessequals" type="valuesType" minOccurs="0"/>
			<xs:element name="and" type="logicalType" minOccurs="0"/>
			<xs:element name="or" type="logicalType" minOccurs="0"/>
			<xs:element name="iscelebrating" minOccurs="0"/>
			<xs:element name="istwosaints" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="getClosestDayType">
		<xs:choice>
			<xs:element ref="date" minOccurs="0"/>
		</xs:choice>
		<xs:attribute name="dayofweek" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="понедельник"/>
					<xs:enumeration value="вторник"/>
					<xs:enumeration value="среда"/>
					<xs:enumeration value="четверг"/>
					<xs:enumeration value="пятница"/>
					<xs:enumeration value="суббота"/>
					<xs:enumeration value="воскресенье"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="weekcount" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:element name="date" type="xs:string"/>
	<!--xs:element name="date" type="xs:gMonthDay"/-->
	<xs:element name="daysfromeaster" type="daysfromeasterType"/>
	<xs:element name="int" type="xs:int"/>
	<xs:element name="equals">
		<xs:complexType>
			<xs:sequence/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="intOutputType">
		<xs:choice>
			<xs:element ref="daysfromeaster" minOccurs="0"/>
			<xs:element ref="int" minOccurs="0"/>
		</xs:choice>
	</xs:complexType>
</xs:schema>

=== irmtim/TypiconOnline.Documentation/XML/Typicon.Migration/Calendar/MenologyAndMovable/--01-06.mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Programming/Documentation/TypiconOnline.Documentation/XML/Rules/RulesModSchema.xsd">
	<if>
		<expression>
			<equals>
				<getdayofweek>
					<date>--01-07</date>
				</getdayofweek>
				<getdayofweek name="понедельник"/>
			</equals>
		</expression>
		<then>
			<modifyday daymove="0" priority="4"/>
		</then>
	</if>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Menology/--02-22.mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Rules/RulesModSchema.xsd">
	<switch>
		<expression>
			<daysfromeaster>
				<date>--02-15</date>
			</daysfromeaster>
		</expression>
		<case>
			<values>
				<int>-63</int>
				<int>-62</int>
				<int>-61</int>
			</values>
			<action>
				<!-- Перенос на -58-й день до Пасхи. Исключаем не попразднество -->
				<modifyday iscelebrating="true">
					<datebydaysfromeaster>
						<int>-58</int>
					</datebydaysfromeaster>
				</modifyday>
				<!-- В самый день фильтрация: без попразднества -->
				<modifyday daymove="0" iscelebrating="false"/>
			</action>
		</case>
		<case>
			<values>
				<int>-60</int>
				<int>-59</int>
				<int>-58</int>
				<int>-57</int>
			</values>
			<action>
				<!-- Перенос на -54-й день до Пасхи. Исключаем не попразднество -->
				<modifyday iscelebrating="true">
					<datebydaysfromeaster>
						<int>-54</int>
					</datebydaysfromeaster>
				</modifyday>
				<!-- В самый день фильтрация: без попразднества -->
				<modifyday daymove="0" iscelebrating="false"/>
			</action>
		</case>
		<case>
			<values>
				<int>-56</int>
				<int>-55</int>
			</values>
			<action>
				<!-- Перенос на -52-й день до Пасхи. Исключаем не попразднество -->
				<modifyday iscelebrating="true">
					<datebydaysfromeaster>
						<int>-52</int>
					</datebydaysfromeaster>
				</modifyday>
				<!-- В самый день фильтрация: без попразднества -->
				<modifyday daymove="0" iscelebrating="false"/>
			</action>
		</case>
		<case>
			<values>
				<int>-54</int>
				<int>-53</int>
			</values>
			<action>
				<!-- Перенос на -50-й день до Пасхи. Исключаем не попразднество -->
				<modifyday iscelebrating="true">
					<datebydaysfromeaster>
						<int>-50</int>
					</datebydaysfromeaster>
				</modifyday>
				<!-- В самый день фильтрация: без попразднества -->
				<modifyday daymove="0" iscelebrating="false"/>
			</action>
		</case>
		<case>
			<values>
				<int>-52</int>
				<int>-51</int>
				<int>-50</int>
			</values>
			<action>
				<!-- Перенос на -49-й день до Пасхи. Исключаем не попразднество -->
				<modifyday iscelebrating="true" priority="4">
					<datebydaysfromeaster>
						<int>-49</int>
					</datebydaysfromeaster>
				</modifyday>
				<!-- В самый день фильтрация: без попразднества -->
				<modifyday daymove="0" iscelebrating="false"/>
			</action>
		</case>
		<case>
			<values>
				<int>-49</int>
				<int>-48</int>
			</values>
			<action>
				<!-- Исключаем попразднество -->
				<modifyday iscelebrating="false" daymove="0"/>
			</action>
		</case>
		<default>
			<!-- Исключаем непопразднество -->
			<modifyday iscelebrating="true" daymove="0"/>
		</default>
	</switch>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Sign/Без знака.mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Rules/RulesModSchema.xsd">
	<if>
		<expression>
			<!--Если воскресенье, то составляем правило особым образом.
				В будущем, надо вынести все в отдельное общее правило CommonRule.-->
			<equals>
				<getdayofweek>
					<date/>
				</getdayofweek>
				<getdayofweek name="воскресенье"/>
			</equals>
		</expression>
		<then>
			<modifyday signname="воскресный_день" daymove="0"/>
		</then>
	</if>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Typicon.Migration/Calendar/MenologyAndMovable/--04-07.mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Programming/Documentation/TypiconOnline.Documentation/XML/Rules/RulesModSchema.xsd">
	<switch>
		<expression>
			<daysfromeaster>
				<date>--04-07</date>
			</daysfromeaster>
		</expression>
		<case>
			<values>
				<int>-29</int>
				<int>-22</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2"/>
			</action>
		</case>
		<case>
			<values>
				<int>-28</int>
			</values>
			<action>
				<modifyday daymove="0"/>
			</action>
		</case>
		<case>
			<values>
				<int>-27</int>
				<int>-20</int>
				<int>-13</int>
			</values>
			<action>
				<modifyday daymove="0"/>
			</action>
		</case>
		<case>
			<values>
				<int>-25</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2"/>
			</action>
		</case>
		<case>
			<values>
				<int>-21</int>
				<int>-14</int>
			</values>
			<action>
				<modifyday daymove="0" islastname="true"/>
			</action>
		</case>
		<case>
			<values>
				<int>-18</int>
			</values>
			<action>
				<modifyday daymove="0"/>
			</action>
		</case>
		<case>
			<values>
				<int>-17</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2"/>
			</action>
		</case>
		<case>
			<values>
				<int>-16</int>
			</values>
			<action>
				<modifyday daymove="0"/>
			</action>
		</case>
		<case>
			<values>
				<int>-15</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2"/>
			</action>
		</case>
		<case>
			<values>
				<int>-8</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2"/>
			</action>
		</case>
		<case>
			<values>
				<int>-7</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2" islastname="true"/>
			</action>
		</case>
		<case>
			<values>
				<int>-6</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2" islastname="true"/>
			</action>
		</case>
		<case>
			<values>
				<int>-5</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2" islastname="true"/>
			</action>
		</case>
		<case>
			<values>
				<int>-4</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2" islastname="true"/>
			</action>
		</case>
		<case>
			<values>
				<int>-3</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2" islastname="true"/>
			</action>
		</case>
		<case>
			<values>
				<int>-2</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2" islastname="true"/>
			</action>
		</case>
		<case>
			<values>
				<int>-1</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2" islastname="true"/>
			</action>
		</case>
		<case>
			<values>
				<int>0</int>
			</values>
			<action>
				<modifyday priority="2" daymove="0"/>
			</action>
		</case>
		<case>
			<values>
				<int>1</int>
				<int>2</int>
				<int>3</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2" islastname="true"/>
			</action>
		</case>
	</switch>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Menology/Неделя пред Богоявлением.mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Rules/RulesModSchema.xsd">
	<switch>
		<expression>
			<getdayofweek><date>--01-07</date></getdayofweek>
		</expression>
		<case>
			<values>
					<getdayofweek name="понедельник"></getdayofweek>
					<getdayofweek name="воскресенье"></getdayofweek>
					<getdayofweek name="вторник"></getdayofweek>
			</values>
			<action>
				
				
			</action>
		</case>
		<default>
			<modifyday signname="воскресный_день" asaddition="true" usefullname="false">
				<shortname>пред Богоявлением</shortname>
				<getclosestday dayofweek="воскресенье" weekcount="-1"><date>--01-19</date></getclosestday>
			</modifyday>
		</default>
	</switch>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Typicon.Migration/Calendar/MenologyAndMovable/--03-25.mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Programming/Documentation/TypiconOnline.Documentation/XML/Rules/RulesModSchema.xsd">
	<switch>
		<expression>
			<daysfromeaster>
				<date>--03-25</date>
			</daysfromeaster>
		</expression>
		<case>
			<values>
				<int>-43</int>
			</values>
			<action>
				<modifyday daymove="-3" priority="5"/>
			</action>
		</case>
	</switch>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Menology/--02-16.mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Rules/RulesModSchema.xsd">
	<switch>
		<expression>
			<daysfromeaster>
				<date>--02-15</date>
			</daysfromeaster>
		</expression>
		<case>
			<values>
				<int>-64</int>
				<int>-58</int>
				<int>-57</int>
				<int>-51</int>
			</values>
			<action>
				<!-- Фильтрация – только попразднество -->
				<modifyday iscelebrating="true" daymove="0"/>
			</action>
		</case>
		<case>
			<values>
				<int>-50</int>
			</values>
			<action>
				<!-- Служба опускается -->
				<modifyday priority="6" daymove="0"/>
			</action>
		</case>
		<case>
			<values>
				<int>-48</int>
			</values>
			<action>
				<!-- Перенос на 1 день назад (-1) с фильтрацией без попразднества-->
				<modifyday daymove="-1" iscelebrating="false"/>
			</action>
		</case>
	</switch>
</rule>

=== irmtim/TypiconOnline.Documentation/XML/Типикон/Menology/--03-08.mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Rules/RulesModSchema.xsd">
	<switch>
		<expression>
			<daysfromeaster>
				<date>--03-08</date>
			</daysfromeaster>
		</expression>
		<!-- В Неделю сыропустную или мясопустную-->
		<case>
			<values>
				<int>-56</int>
				<int>-49</int>
			</values>
			<action>
				<modifyday daymove="0" priority="3"/>
			</action>
		</case>
		<!-- В субботу мясопустную-->
		<case>
			<values>
				<int>-57</int>
			</values>
			<action>
				<modifyday daymove="-1" priority="3"/>
			</action>
		</case>
		<!-- В понедельник или вторник сырной седмицы-->
		<!-- В четверг сырной седмицы-->
		<case>
			<values>
				<int>-55</int>
				<int>-54</int>
				<int>-52</int>
			</values>
			<action>
				<!-- ничего не делаем -->
				<modifyday daymove="0" priority="3"/>
			</action>
		</case>
		<!-- В среду сырной седмицы-->
		<!-- В пятницу сырной седмицы-->
		<case>
			<values>
				<int>-53</int>
				<int>-51</int>
			</values>
			<action>
				<modifyday daymove="-1" priority="3"/>
			</action>
		</case>
		<!-- В субботу сыропустную-->
		<case>
			<values>
				<int>-50</int>
			</values>
			<action>
				<modifyday daymove="0" priority="4"/>
			</action>
		</case>
		<!-- С понедельника по пятницу первой седмицы Великого Поста-->
		<!-- В субботу первой седмицы Поста-->
		<case>
			<values>
				<int>-48</int>
				<int>-47</int>
				<int>-46</int>
				<int>-45</int>
				<int>-44</int>
				<int>-43</int>
			</values>
			<action>
				<modifyday priority="4">
					<datebydaysfromeaster>
						<int>-43</int>
					</datebydaysfromeaster>
					<modifyreplacedday kind="menology">
						<date/>
					</modifyreplacedday>
				</modifyday>
			</action>
		</case>
		<!-- В пятницу сырной седмицы-->
		<case>
			<values>
				<int>-53</int>
				<int>-51</int>
			</values>
			<action>
				<modifyday daymove="-1" priority="3"/>
			</action>
		</case>
		<!-- 1 Неделя Поста-->
		<!-- Понедельник 2, 3, 4 седмицы Поста -->
		<!-- Един от дней постных -->
		<case>
			<values>
				<int>-42</int>
			</values>
			<action>
				<modifyday daymove="0" priority="4"/>
			</action>
		</case>
		<!-- В субботу 2, 3 Поста -->
		<case>
			<values>
				<int>-36</int>
				<int>-29</int>
			</values>
			<action>
				<modifyday daymove="0" priority="2"/>
			</action>
		</case>
		<!-- В недели 2, 3 Поста -->
		<case>
			<values>
				<int>-35</int>
				<int>-28</int>
			</values>
			<action>
				<modifyday daymove="0" priority="4"/>
			</action>
		</case>
		<!-- иначе -->
		<default>
			<modifyday daymove="0" priority="3"/>
		</default>
	</switch>
</rule>
